USE [master] 
ALTER DATABASE [AxDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
RESTORE DATABASE [AxDB] FROM DISK = N'J:\MSSQL_BACKUP\[DBNAME].bak' WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 5, ENABLE_BROKER 
ALTER DATABASE [AxDB] SET MULTI_USER
