USE master;
ALTER DATABASE [AxDB] SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE
CREATE DATABASE [SnapshotName] ON
(NAME = [AxDBFileName],  
FILENAME = 'I:\MSSQL_BACKUP\[SnapshotName].ss' )
AS SNAPSHOT OF [AxDB];
GO
